from ..service.orders.ingredient_service import IngredientService
from ..service.orders.dish_service import DishService
from ..service.orders.sportsman_service import SportsmanService
from ..service.orders.doctors_contact_service import DoctorsContactService
from ..service.orders.doctor_specialization_service import DoctorSpecializationService
from ..service.orders.coach_specialization_service import CoachSpecializationService
from ..service.orders.coach_service import CoachService
from ..service.orders.coaches_contact_service import CoachesContactService
from ..service.orders.program_service import ProgramService
from ..service.orders.sportsman_has_program_service import SportsmanHasProgramService
from ..service.orders.doctor_service import DoctorService
from ..service.orders.dish_has_ingredient_service import DishHasIngredientService