swagger: "2.0"
info:
  title: Coach API
  version: "1.0"
  description: API for managing coach specializations


/coach_specialization:
  get:
    tags: [Coach Specialization]
    summary: Get all specializations
    responses:
      200:
        description: List of coach specializations

  post:
    tags: [Coach Specialization]
    summary: Add specialization
    parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            id: { type: integer }
            name: { type: string }
          required: [id, name]
    responses:
      200:
        description: Specialization added

/coach_specialization/{coach_specialization_id}:
  get:
    tags: [Coach Specialization]
    summary: Get specialization by ID
    parameters:
      - in: path
        name: coach_specialization_id
        required: true
        type: integer
    responses:
      200:
        description: A single specialization

  patch:
    tags: [Coach Specialization]
    summary: Update specialization
    parameters:
      - in: path
        name: coach_specialization_id
        required: true
        type: integer
    responses:
      200:
        description: Updated specialization

  delete:
    tags: [Coach Specialization]
    summary: Delete specialization
    parameters:
      - in: path
        name: coach_specialization_id
        required: true
        type: integer
    responses:
      200:
        description: Deleted specialization

/coach_specialization/{coach_specialization_id}/coaches:
  get:
    tags: [Coach Specialization]
    summary: Get coaches by specialization
    parameters:
      - in: path
        name: coach_specialization_id
        required: true
        type: integer
    responses:
      200:
        description: List of coaches for specialization
